### PR TITLE
Specify commit message practices

### LINKED ISSUE #324: Create standards for how to merge PRs (squash vs. rebase)

### PR DESCRIPTION
**Pull request by taymonbeal**
This only works if all committers are on board with it, so I've added everyone in @rtcharity/tech as a reviewer. Please review at your earliest convenience.

Fixes #324 and #327.

### CODE REVIEW

**Comment by taymonbeal** [comment]
Shouldn't. I've been doing this stuff the whole time, including for small updates.

**Comment by michaltrzesimiech** [comment]
Fine by me!

**Comment by taymonbeal** [comment]
I'm honestly not sure how worried we are about IP issues. I had us institute the DCO because before that the practice was to make volunteers sign IP assignment agreements with Rethink Charity, which I personally am not allowed to do (without a bunch of paperwork) and which is generally considered unfriendly for an open source project. It was agreed that the DCO was an adequate substitute for this. @michaltrzesimiech, do you have any thoughts?

"Rebase" here means rebasing all the commits in a PR onto master one at a time, as opposed to squashing them all into a single commit. I think we should consistently do one or the other, and a single commit on master per PR seems like the more common practice, and generally nicer since usually nobody's generally going to care about all those intermediate commits. Do you disagree? (Note that contributors can and should still rebase their own branches to resolve merge conflicts.)

**Comment by sebgrebe** [comment]
> Do you disagree?

No, not at all, was just genuinely curious :) Thanks for the explanation

**Comment by michaltrzesimiech** [comment]
> It was agreed that the DCO was an adequate substitute for this. @michaltrzesimiech, do you have any thoughts?

I remember this was the agreed upon solution. I'm happy to consult this with our lawyers if there's anything that could work better for any of us here.

**Comment by taymonbeal** [comment]
You could ask them if they think we actually need this, and if not we could get rid of it since it's a minor speedbump to contributing. But not a big deal either way.

**Pull request merged**
