### PR TITLE
1256 checkbox privacy policy

### LINKED ISSUE #1256: Add checkbox for agreeing to privacy policy and community guidelines
### Acceptance criteria
* [ ] On sign up, users need to tick a checkbox agreeing to privacy policy and community guidelines
  * Wording: "I agree to the Privacy Policy and the Community Guidelines"
* [ ] Community guidlines page added
* [ ] Take note of timestamp when this was deployed so that we can distinguish between users who have agreed and those who haven't

### PR DESCRIPTION
**Pull request by sebgrebe**
* Add community guidelines  
* Add checkbox that makes user agree to community guidelines and privacy policy before signing up  
* Reformats footer to have links at top (rather than bottom) if number of links unequal, i.e., looks like this:   
image  
* Sets all existing user's "privacy_policy_agreed" to true as we consider them having agreed to the privacy policy as it is currently linked above the sign up button (like this):  
 
image
 
* Can be QAed on stage

Closes #1256

### CODE REVIEW

**Comment by viktor-yunenko** [comment]
Overall it looks good, the only thing I recommend to adjust is to utilize bs5 form control for the checkbox, it adds the default styles and UX features 👍 

image

**Comment by sebgrebe** [comment]
Thanks, @victor-yunenko, implemented your comment

**Comment by sebgrebe** [comment]
> 
> 
> Overall it looks good, the only thing I recommend to adjust is to utilize bs5 form control for the checkbox, it adds the default styles and UX features 👍
> 
> image

@victor-yunenko, you mentioned verbally that my changes in reaction to your comment weren't quite what you had in mind. Could you put here what you exactly had in mind? I suspect it is about exactly following the pattern in ```profile_update.html```, i.e.,

 ```
<div class="col col-bool-with-margin-top">
              {% include 'includes/field.html' with form=form field=form.open_to_job_offers %}
            </div>
```
The reason I didn't use this pattern is that the field name is not what we want to display next to the checkbox, unlike for example in the case of "Open to job offers"

**Comment by sebgrebe** [comment]
@victor-yunenko, just updated so that is uses the ```includes/field.html``` code, which enables clicking on the tag (and also allows for less boilerplate html code)

**Review by viktor-yunenko — APPROVED** [review]

**Pull request merged**
