### PR TITLE
Add optional field "Past organisers" to local group profiles

### LINKED ISSUE #726: Add optional field "Past organisers" to local group profiles

### PR DESCRIPTION
**Pull request by david-mears**
This PR also implements the below note - that is, making it actually true.

Previously, organisers whose profiles were not public were not visible on the group details view (though they were visible on the group edit view), even to those who are organisers of the same group.

Now, organisers of the group will be visible if they're a (past/present) organiser AND the current user is a current organiser. Or if their profile is public.

privacy

Fixes: #726

### CODE REVIEW

**Comment by david-mears** [comment]
Note: No tests were written, I haven't got jasmine to work on my machine yet.

**Comment by taymonbeal** [comment]
Is it supposed to be possible for someone to be both a present and past organizer? Are past organizers supposed to have any special permissions?

**Comment by taymonbeal** [comment]
@michaltrzesimiech 

If past organizers have no special permissions, then I'm somewhat leaning towards having them be a separate kind of member rather than a separate kind of organizer.

**Comment by michaltrzesimiech** [comment]
I agree. It would be ideal if past organizers were members rather than organizers.

**Comment by vagarwalla** [comment]
- Have a new relationship - Person-Group - past organiser-ship
- No rights to edit the group etc 
- Not sure how useful it is?
- Backlog 
- See discussion in #726

**Comment by sebgrebe** [comment]
closing as progress has been stalling

**Pull request closed without merging**
