### PR TITLE
Switch geocoding from Nominatim to Google Maps

### LINKED ISSUE #264: Migrate from Nominatim to Google Maps
Nominatim is very much not intended for production traffic, and has very strict rate limits that we're quite likely to run into. They blocked my IP while I was running the Airtable migration script on my laptop.

### PR DESCRIPTION
**Pull request by patbl**
Google Maps charges $5 per 1k requests (half a cent per request). Nominatim limits requests to "an absolute maximum of 1 request per second" (https://operations.osmfoundation.org/policies/nominatim/). Ostensibly, the worry is that we might exceed that limit.

Google gives us $200 in credit per month, which means we can make 1,334 calls per day for free.

For the geocoding to work, the environment `GOOGLE_MAPS_API_KEY` must be set. I tested this out with my own API key, which I got by following these instructions:

https://developers.google.com/maps/documentation/geocoding/get-api-key

For the API key to work, I think I needed to sign up for a paid account.

To test this, I updated the location of my profile and I created and updated a local group. The changes were reflected in the map each time.

Fixes #264.
May fíx #582 and #807.

### CODE REVIEW

**Comment by michaltrzesimiech** [comment]
Many thanks, @patbl! Looks good to me. @taymonbeal could I ask your perspective as well?

**Comment by taymonbeal** [comment]
We can't merge this right now because the tests are failing. Please correct this and then I can take another look.

**Comment by patbl** [comment]
A build for a different branch [recently failed](https://dev.azure.com/rtcharity/eahub.org/_build/results?buildId=136) with the same error:

```
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/site-packages/storages/backends/azure_storage.py", line 8, in <module>
    from azure.common import AzureMissingResourceHttpError
ModuleNotFoundError: No module named 'azure.common'
```

This is the same error that David Mears and I had in our development environments (without any code changes):

https://rtcharity.slack.com/archives/CHGV507EW/p1572811476001800

**Comment by vagarwalla** [comment]
We need to rebase this & make sure everything passes the checks before accepting merge request.,

**Comment by sebgrebe** [comment]
closing as progress has been stalling

**Pull request closed without merging**
