### PR TITLE
Profile: Add "Open to couchsurfing" checkbox

### LINKED ISSUE #802: Add a couchsurfing box to profile
It should say "I may offer a short stay at my place"

### PR DESCRIPTION
**Pull request by patbl**
Fixes #802.

I think it's a bit odd to split up the speaker-related things. I think it would be better to put the couchsurfing checkbox before "Available as speaker" or after "Topics I speak about" on the profile-edit page:

image

image

### CODE REVIEW

**Comment by patbl** [comment]
@Richenda

**Comment by Richenda** [comment]
Oh yes, I didn’t mean to split. That sounds like a better suggestion @patbl 👍🏻

**Comment by patbl** [comment]
Do you have a preference for placement above or below the speaking-related items?

Above:

image

Below:

image

**Comment by Richenda** [comment]
Below, IMO

**Comment by patbl** [comment]
OK, that's what I went with.

**Pull request merged**
