### PR TITLE
Integrate AdSense

### PR DESCRIPTION
**Pull request by michaltrzesimiech**
Closes https://github.com/rtcharity/eahub.org/issues/704

### CODE REVIEW

**Comment by michaltrzesimiech** [comment]
We don't, this step is required to generate ads.txt

**Comment by michaltrzesimiech** [comment]
Long story short, we generate that in Ad Manager, but `To sign up for Google Ad Manager, you must first have a Google AdSense account.`. To activate AdSense account, we need to include this snippet in our <head>.

https://support.google.com/admanager/answer/7544382

**Comment by michaltrzesimiech** [comment]
Or, we could maybe just use a random ads.txt

**Comment by michaltrzesimiech** [comment]
Curiously, we no longer have an option to enable the thing we don't want in the first place, because they discovered one of these issues https://support.google.com/adsense/answer/1348688?hl=en and we should get rid of it.

**Comment by michaltrzesimiech** [comment]
I currently opt for finding another way to implement ads.txt.

**Comment by taymonbeal** [comment]
We don't need an AdSense account, it was never the plan to sign up for one. I'll explain in more detail later.

**Pull request closed without merging**
