### PR TITLE
Point to reactivation email

### LINKED ISSUE #432: Correct "the old profiles don't exist anymore" verbiage

### PR DESCRIPTION
**Pull request by sebgrebe**
Signed-off-by: Sebastian <sebbecker@gmx.net>

closes #432 

Don't merge before #436 has been merged.

### CODE REVIEW

**Comment by sebgrebe** [comment]
> Maybe say something about how you can still do a password reset if you don't have the email? Idk how to do this without too much verbiage though

done

**Comment by sebgrebe** [comment]
@michaltrzesimiech said we're probably announcing 10 am London time tomorrow (Tue, 2/4). Should we merge this PR now and deploy?

**Comment by taymonbeal** [comment]
We're not ready to launch today.

**Comment by taymonbeal** [comment]
@sebgrebe, this has grown some merge conflicts again. Also, would you mind changing it to be less definite about whether the reader received an email? Some people will run across this before getting the email.

**Comment by sebgrebe** [comment]
> @sebgrebe, this has grown some merge conflicts again. Also, would you mind changing it to be less definite about whether the reader received an email? Some people will run across this before getting the email.

done

**Comment by taymonbeal** [comment]
Are you sure that's the right URL name?

**Comment by sebgrebe** [comment]
> Are you sure that's the right URL name?

You're right, thanks! Fixed.

**Pull request merged**
