### PR TITLE
Render URLs in free-text fields as links

### PR DESCRIPTION
**Pull request by taymonbeal**
Fixes: #461

### CODE REVIEW

**Comment by michaltrzesimiech** [comment]
Shouldn't we implement spam protection first before allowing this?

**Comment by taymonbeal** [comment]
I don't know. We do use `rel=nofollow` so that mitigates things. Do we generally have the spam problem under control? We aren't going to have automated spam filtering until after the freeze but we could put this on ice until then if desired.

**Comment by sebgrebe** [comment]
> I think this isn't necessary as linkify already implements this. Every div that has linkify as a CSS class turns URLs into links. So for example, the community panel on a profile page has linkified URLs because the div encompassing all panels has linkify as a CSS class.

@taymonbeal, what do you think about this? Can we close this PR?

**Comment by taymonbeal** [comment]
I think it's preferable to do this on the server; the server-side implementation implements nofollow, which we need for spam reasons, and also doesn't slow down the page by forcing the user's browser (which might be a low-end smartphone) to do all the work. I've added a commit to remove linkify from the codebase.

**Comment by taymonbeal** [comment]
Fixed.

**Pull request merged**
