### PR TITLE
Force email verification on signup + add it to admin

### PR DESCRIPTION
**Pull request by viktor-yunenko**

### CODE REVIEW

**Comment by sebgrebe** [comment]
Can we make the wording on the default text a bit nicer? Currently:  

```
Hello from EA Hub!

You're receiving this e-mail because user Sebastian Becker has given your e-mail address to register an account on eahub.org.

To confirm this is correct, go to [LINK]

Thank you for using EA Hub!
eahub.org
```

Rather:

```
Dear [user name],

We're happy you sign up forthe EA Hub. You just need to verify your email address [here].

Thank you,

EA Hub
```

**Review by sebgrebe — APPROVED** [review]
All good, just make sure to  
- [x] move footer into separate component  
- [x] Rephrase email  
- [x] Create a new ticket for adding profile logs for verification

**Comment by viktor-yunenko** [comment]
I also confirmed that the existing users who didn't verify their email will also be redirected to the respective verification page on login:


image

**Comment by viktor-yunenko** [comment]
I also handled all the aforementioned points 👍 

Plus I fixed the e2e test and added visual & content improvements.

I can do final testing and a deployment tomorrow morning then. I'm looking forward to the spammers' reaction :)

**Pull request merged**
