### PR TITLE
Extend & reorder users organizations

### PR DESCRIPTION
**Pull request by mattg95**
There is a discussion of which charities to include here: https://github.com/rtcharity/eahub.org/issues/995. I have added all the ones that Vaidehi has listed, but no more.

### CODE REVIEW

**Review by sebgrebe — CHANGES_REQUESTED** [review]
Thanks for this.
It would be nice if we could order them alphabetical on the drop down, independent of their enum number

image

**Comment by victor-yunenko** [comment]
> It would be nice if we could order them alphabetical on the drop down, independent of their enum number

FYI with django models we can set default order to the `name` field.

**Comment by victor-yunenko** [comment]
FYI I think you can order it by reordering the python enum members, eg instead of
```python
    THE_LIFE_YOU_CAN_SAVE = 30
    WILD_ANIMAL_INITIATIVE = 31
    ALLFED = 32
```
we can write
```python
    ALLFED = 32
    THE_LIFE_YOU_CAN_SAVE = 30
    WILD_ANIMAL_INITIATIVE = 31
```

**Comment by mattg95** [comment]
@victor-yunenko I've tried reordering the python numbers but it doesn't change the order of the drop down, unless I'm missing something. There is a new issue open moving from enums to models: https://github.com/rtcharity/eahub.org/issues/1068. I could take on this issues as I could then order the choices in the model using `ordering=["name"]`. I could also refactor the solution for adding new cause areas which is currently open https://github.com/rtcharity/eahub.org/issues/949 using the same approach.

**Comment by victor-yunenko** [comment]
@mattg95, interesting - did you try to change the order of attributes along with `labels`?

**Comment by victor-yunenko** [comment]
Probably the migration to models is a bigger feature that we should address later on 👌

**Comment by victor-yunenko** [comment]
hi @mattg95! did you have a chance to try to reorder the labels?

**Comment by mattg95** [comment]
> hi @mattg95! did you have a chance to try to reorder the labels?

@victor-yunenko I have tried arranging the attributes and the labels but the only thing that seems to change the order is to change the actual enum number, which obviously is not what we want. Do you know a way of reordering them?

**Comment by mattg95** [comment]
The way I did it when adding cause areas was to make a function that rearrange them like so:
Screenshot from 2020-12-28 20-13-02

**Comment by sebgrebe** [comment]
@mattg95, having discussed this with @victor-yunenko and @vagarwalla, could we add all the orgs [here](https://www.notion.so/ae330bb9deac4186b7528b84939d5448), in alphabetical order? (To see how to do alphabetical ordering, see my change on your PR for causes areas)

**Comment by mattg95** [comment]
@sebgrebe I've added all the orgs from [here](https://www.notion.so/ae330bb9deac4186b7528b84939d5448). One problem I ran into was overrunning  line length character limits (flake8 errors). I've shortened some of the names of organisations so that we can still have full length labels (e.g. see last commit). Is this ok, or will it mess up the db, like if the names are referenced as a key in the db?

**Review by sebgrebe — APPROVED** [review]

**Pull request merged**
