### PR TITLE
Integrate github actions #1031

### PR DESCRIPTION
**Pull request by victor-yunenko**

### CODE REVIEW

**Comment by sebgrebe** [comment]
Bit hard to review just by looking at the code, can I see this in action somewhere? Or we can only use the github actions once this is merged?

**Review by sebgrebe — CHANGES_REQUESTED** [review]
Bit hard to review just by looking at the code, can I see this in action somewhere? Or we can only use the github actions once this is merged?

**Comment by victor-yunenko** [comment]
Sure, they even were running on PRs before, but then I created a new branch (without changes) and they stopped 🤔 

You can see the runs history here - https://github.com/rtcharity/eahub.org/actions

The logs - https://github.com/rtcharity/eahub.org/runs/1559732966?check_suite_focus=true

**Review by sebgrebe — APPROVED** [review]
@victor-yunenko demoed and explained how this works to me, looks good.

**Pull request merged**
