### PR TITLE
Add projects page

### LINKED ISSUE #865: Add EA Hub Asana space
- [ ] Replace the grey EA Projects icon on the front page with https://drive.google.com/open?id=1WHhCiOjSplI54NOojp7c_72cPd2JMrYM

- [ ] Create a new webpage for EA Projects. On the new page, please add the following text: The Hub team is looking for volunteers to extend our functionality for projects. In the meantime, EA orgs can join this Asana space. The words 'this Asana space' should link to this form: http://is.gd/asanaforea

### PR DESCRIPTION
**Pull request by sebgrebe**
- Adds new "EA projects" page, which links to EAHub Asana space
Screen Shot 2020-04-13 at 15 00 19
- Replaces greyed out "EA projects" link on homepage with working on to new EA projects page
- Closes #865 

@cafelow @Richenda Does this look OK? Personally, I find the Asana space page it links to a bit confusing, i.e., it's not clear to me what's being offered. Related to this, I wonder whether we could on our page put some explanation of what the purpose of this Asana page is

### CODE REVIEW

**Comment by cafelow** [comment]
Yeah, I agree it is confusing Seb. To be honest, I don't really think the Asana offer fits here at all, but I don't know where else it should go and we have promised Remmelt that we'd put it somewhere. 

What I would like to go on the page is this:
1. A sentence or two about what the projects feature will do. Otherwise, the ask for volunteers won't be appealing - and it would be really cool to get people excited about new features. @Richenda do you have any suitable text?
2. The ask for volunteers as is currently written (or you could include a little more of the skills required... e.g. are you looking for just software developers, or is there a wider range of volunteers). 
3. Then the Asana offer could read
"If you are currently running an EA project or organisation you can get access to Asana at a very low cost by applying here".

**Comment by Richenda** [comment]
Yes, I agree about the Asana link. When I made the issue to get Remmelt's link added I sent him some suggestions to alter the information on the link to be clearer. But it's still not very clear. I think the best thing would be if he could write a blurb explaining what it's for for us to include.

Now that the Projects page is calling for volunteers, I think it would be better if the Asana link wasn't there. It will just add confusion. My sense is that the only people who would be interested are developed groups that are professionalised and have gotten as far as registering as non profits. If there is a section in the resources for late stage groups, perhaps it could be mentioned there instead?

For the Projects functionality, I can write some text this week to clarify.

**Comment by Richenda** [comment]
One other idea is adding a section in the Hub somewhere that can serve as a kind of community noticeboard of sorts. I haven't thought it over, this is just brainstorming.

**Comment by cafelow** [comment]
Thanks Richenda, that would be great to have some explanation there. 
I could add a link to the Asana space in the resources within the section on organising large EA groups - but it won't be very visible, and probably won't get any clicks - there just aren't THAT many groups who would have more than 15 organisers/complex project structures to justify a paid Asana. 

Having said that, there probably won't be many clicks on his form from the Projects page either. I feel like we should probably go back to Remmelt and find out how the Hub could really help with his project.

**Comment by cafelow** [comment]
Community noticeboard would be really cool! 
I'm a little worried about the time it would take to keep it updated and useful, but in principle I think it would be great!

**Comment by Richenda** [comment]
Sure, I'll get to that
> Community noticeboard would be really cool!
> I'm a little worried about the time it would take to keep it updated and useful, but in principle I think it would be great!

Yeh that's my concern too.

**Comment by sebgrebe** [comment]
@cafelow and @Richenda Thanks for discussing this, let me know when you've come to a conclusion

**Comment by Richenda** [comment]
>  Thanks for discussing this, let me know when you've come to a conclusion
The conclusion was just that the Asana link would be removed (Catherine has placed it in the resources area for advanced stage groups), and so now the 'Projects' page will exclusively have a blurb about the feature and call for a volunteer. I will write this.

**Comment by Richenda** [comment]
Full disclosure, I have a presentation to research and write for an interview in a few days. But I'll try to move on this as fast as I can.

**Comment by sebgrebe** [comment]
Parked for the moment

**Pull request closed without merging**
